name: Continuous Integration

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Backend setup
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Set up database
        working-directory: ./backend
        run: mkdir -p ./db

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Generate Prisma client
        working-directory: ./backend
        run: npx prisma generate

      - name: Build and test backend
        working-directory: ./backend
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          DATABASE_URL: "file:./db/dev.db"
          PORT: ${{ secrets.PORT }}
        run: |
          npm run build
          npm run test

      # Frontend setup
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
